FROM ubuntu:18.04

WORKDIR /usr/src/app

COPY . .

RUN apt-get update && apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash && apt-get install -y nodejs

RUN npm install && npm run build && npm install -g serve

RUN useradd -m devuser && chown devuser /usr/src/app

USER devuser

CMD ["serve", "-s", "-l", "5000", "build"]